export type Chapter1AssetDefinition = Readonly<{
  path: string;
  width: number;
  height: number;
  placeholderColor: number;
  sourceAvailable: boolean;
}>;

export const CHAPTER1_ASSET_MANIFEST: Readonly<Record<string, Chapter1AssetDefinition>> = {
  'chapter1-floor-tileset': {
    path: new URL('./tiles/floor_tileset.png', import.meta.url).href,
    width: 256,
    height: 32,
    placeholderColor: 0x5b3826,
    sourceAvailable: true,
  },
  'chapter1-wall-tileset': {
    path: new URL('./tiles/wall_tileset_raised.png', import.meta.url).href,
    width: 256,
    height: 32,
    placeholderColor: 0x6c5a5a,
    sourceAvailable: true,
  },
  'chapter1-wall-top': {
    path: new URL('./tiles/wall-kit-long/wall_top.png', import.meta.url).href,
    width: 32,
    height: 64,
    placeholderColor: 0x705747,
    sourceAvailable: true,
  },
  'chapter1-wall-bottom': {
    path: new URL('./tiles/wall-kit-long/wall_bottom_dim.png', import.meta.url).href,
    width: 32,
    height: 48,
    placeholderColor: 0x4b352b,
    sourceAvailable: true,
  },
  'chapter1-wall-left': {
    path: new URL('./tiles/wall-kit-long/wall_left_compact.png', import.meta.url).href,
    width: 48,
    height: 32,
    placeholderColor: 0x6f5543,
    sourceAvailable: true,
  },
  'chapter1-wall-right': {
    path: new URL('./tiles/wall-kit-long/wall_right_compact.png', import.meta.url).href,
    width: 48,
    height: 32,
    placeholderColor: 0x4b362e,
    sourceAvailable: true,
  },
  'chapter1-wall-corner-tl': {
    path: new URL('./tiles/wall-kit-long/wall_corner_tl_transition.png', import.meta.url).href,
    width: 48,
    height: 48,
    placeholderColor: 0x6f5543,
    sourceAvailable: true,
  },
  'chapter1-wall-corner-tr': {
    path: new URL('./tiles/wall-kit-long/wall_corner_tr_transition.png', import.meta.url).href,
    width: 48,
    height: 48,
    placeholderColor: 0x6f5543,
    sourceAvailable: true,
  },
  'chapter1-wall-corner-bl': {
    path: new URL('./tiles/wall-kit-long/wall_corner_bl_dim.png', import.meta.url).href,
    width: 48,
    height: 48,
    placeholderColor: 0x4b362e,
    sourceAvailable: true,
  },
  'chapter1-wall-corner-br': {
    path: new URL('./tiles/wall-kit-long/wall_corner_br_dim.png', import.meta.url).href,
    width: 48,
    height: 48,
    placeholderColor: 0x4b362e,
    sourceAvailable: true,
  },
  'chapter1-wall-top-window': {
    path: new URL('./tiles/wall-kit-v2/wall_top_window_recess.png', import.meta.url).href,
    width: 64,
    height: 40,
    placeholderColor: 0x2a252b,
    sourceAvailable: true,
  },
  'chapter1-wall-bottom-doorway': {
    path: new URL('./tiles/wall-kit-long/wall_bottom_doorway_dim.png', import.meta.url).href,
    width: 96,
    height: 48,
    placeholderColor: 0x2a252b,
    sourceAvailable: true,
  },
  'chapter1-bed': {
    path: new URL('./furniture/bed.png', import.meta.url).href,
    width: 64,
    height: 96,
    placeholderColor: 0x8e6a58,
    sourceAvailable: true,
  },
  'chapter1-nightstand': {
    path: new URL('./furniture/nightstand.png', import.meta.url).href,
    width: 32,
    height: 64,
    placeholderColor: 0x946341,
    sourceAvailable: true,
  },
  'chapter1-grandfather-clock': {
    path: new URL('./furniture/grandfather_clock.png', import.meta.url).href,
    width: 64,
    height: 96,
    placeholderColor: 0xb68642,
    sourceAvailable: true,
  },
  'chapter1-window': {
    path: new URL('./furniture/window.png', import.meta.url).href,
    width: 96,
    height: 64,
    placeholderColor: 0x263c5d,
    sourceAvailable: true,
  },
  'chapter1-portrait': {
    path: new URL('./furniture/portrait.png', import.meta.url).href,
    width: 32,
    height: 64,
    placeholderColor: 0x8b6a4c,
    sourceAvailable: true,
  },
  'chapter1-desk': {
    path: new URL('./furniture/desk_topdown.png', import.meta.url).href,
    width: 64,
    height: 96,
    placeholderColor: 0x704327,
    sourceAvailable: true,
  },
  'chapter1-chair': {
    path: new URL('./furniture/chair.png', import.meta.url).href,
    width: 32,
    height: 64,
    placeholderColor: 0x593521,
    sourceAvailable: true,
  },
  'chapter1-rug': {
    path: new URL('./furniture/rug.png', import.meta.url).href,
    width: 192,
    height: 96,
    placeholderColor: 0x5a2832,
    sourceAvailable: true,
  },
  'chapter1-bookshelf-standing': {
    path: new URL('./puzzle/bookshelf_standing.png', import.meta.url).href,
    width: 128,
    height: 96,
    placeholderColor: 0x71421f,
    sourceAvailable: true,
  },
  'chapter1-bookshelf-fallen': {
    path: new URL('./puzzle/bookshelf_fallen.png', import.meta.url).href,
    width: 128,
    height: 96,
    placeholderColor: 0x8b5528,
    sourceAvailable: true,
  },
  'chapter1-door-closed': {
    path: new URL('./puzzle/door_closed.png', import.meta.url).href,
    width: 96,
    height: 96,
    placeholderColor: 0x633719,
    sourceAvailable: true,
  },
  'chapter1-door-open': {
    path: new URL('./puzzle/door_open.png', import.meta.url).href,
    width: 96,
    height: 96,
    placeholderColor: 0xb48745,
    sourceAvailable: true,
  },
  'chapter1-pocket-watch': {
    path: '/src/assets/chapter1/items/pocket_watch.png',
    width: 32,
    height: 32,
    placeholderColor: 0xd8b65a,
    sourceAvailable: false,
  },
  'chapter1-key': {
    path: new URL('./puzzle/key.png', import.meta.url).href,
    width: 32,
    height: 32,
    placeholderColor: 0xe5c86c,
    sourceAvailable: true,
  },
  'chapter1-potted-plant': {
    path: new URL('./decor/potted_plant.png', import.meta.url).href,
    width: 32,
    height: 64,
    placeholderColor: 0x4f764c,
    sourceAvailable: true,
  },
  'chapter1-crate': {
    path: new URL('./decor/crate.png', import.meta.url).href,
    width: 32,
    height: 64,
    placeholderColor: 0x8f6138,
    sourceAvailable: true,
  },
  'chapter1-barrel': {
    path: new URL('./decor/barrel.png', import.meta.url).href,
    width: 32,
    height: 32,
    placeholderColor: 0x704528,
    sourceAvailable: true,
  },
};
