import { CHAPTER1_ASSET_MANIFEST } from '../assets/chapter1/manifest';
import type { ChapterVisualTheme } from './chapter-visual-theme';
import { WALL_ATTACHED_BOOKSHELF_VISUAL } from './manor-shared-visuals';

export const CHAPTER4_VISUAL_THEME: ChapterVisualTheme = {
  chapterId: 'chapter-04',
  assets: {
    ...CHAPTER1_ASSET_MANIFEST,
    'chapter4-portrait-normal': {
      path: new URL('../assets/chapter4/portrait_normal.png', import.meta.url).href,
      width: 48,
      height: 64,
      placeholderColor: 0x8b6a4c,
      sourceAvailable: true,
    },
    'chapter4-portrait-changed': {
      path: new URL('../assets/chapter4/portrait_changed.png', import.meta.url).href,
      width: 48,
      height: 64,
      placeholderColor: 0xb68642,
      sourceAvailable: true,
    },
    'chapter4-book-normal': {
      path: new URL('../assets/chapter4/book_normal.png', import.meta.url).href,
      width: 64,
      height: 52,
      placeholderColor: 0x8e6a58,
      sourceAvailable: true,
    },
    'chapter4-book-changed': {
      path: new URL('../assets/chapter4/book_changed.png', import.meta.url).href,
      width: 64,
      height: 52,
      placeholderColor: 0xb68642,
      sourceAvailable: true,
    },
    'chapter4-painting-normal': {
      path: new URL('../assets/chapter4/painting_normal.png', import.meta.url).href,
      width: 64,
      height: 64,
      placeholderColor: 0x6f5543,
      sourceAvailable: true,
    },
    'chapter4-painting-missing': {
      path: new URL('../assets/chapter4/painting_missing.png', import.meta.url).href,
      width: 64,
      height: 64,
      placeholderColor: 0xb68642,
      sourceAvailable: true,
    },
    'chapter4-clock-static': {
      path: new URL('../assets/chapter4/clock_static.png', import.meta.url).href,
      width: 32,
      height: 64,
      placeholderColor: 0xb68642,
      sourceAvailable: true,
    },
    'chapter4-code-lock': {
      path: new URL('../assets/chapter4/code_lock.png', import.meta.url).href,
      width: 64,
      height: 48,
      placeholderColor: 0xb68642,
      sourceAvailable: true,
    },
    'chapter4-door-left-open': {
      path: new URL('../assets/chapter4/doors/door_left_open.png', import.meta.url).href,
      width: 48,
      height: 64,
      placeholderColor: 0x633719,
      sourceAvailable: true,
    },
    'chapter4-door-right-closed': {
      path: new URL('../assets/chapter4/doors/door_right_closed.png', import.meta.url).href,
      width: 48,
      height: 64,
      placeholderColor: 0x24354a,
      sourceAvailable: true,
    },
    'chapter4-door-right-open': {
      path: new URL('../assets/chapter4/doors/door_right_open.png', import.meta.url).href,
      width: 48,
      height: 64,
      placeholderColor: 0x24354a,
      sourceAvailable: true,
    },
    'chapter4-low-record-cabinet': {
      path: new URL('../assets/chapter4/decor/low_record_cabinet.png', import.meta.url).href,
      width: 64,
      height: 32,
      placeholderColor: 0x6d3d1f,
      sourceAvailable: true,
    },
    'chapter4-small-writing-desk': {
      path: new URL('../assets/chapter4/decor/small_writing_desk.png', import.meta.url).href,
      width: 64,
      height: 32,
      placeholderColor: 0x704323,
      sourceAvailable: true,
    },
    'chapter4-wall-frame-small-01': {
      path: new URL('../assets/chapter4/decor/wall_frame_small_01.png', import.meta.url).href,
      width: 32,
      height: 32,
      placeholderColor: 0x9a6a35,
      sourceAvailable: true,
    },
    'chapter4-wall-frame-small-02': {
      path: new URL('../assets/chapter4/decor/wall_frame_small_02.png', import.meta.url).href,
      width: 32,
      height: 32,
      placeholderColor: 0x76502f,
      sourceAvailable: true,
    },
    'chapter4-wall-candle-variant': {
      path: new URL('../assets/chapter4/decor/wall_candle_variant.png', import.meta.url).href,
      width: 32,
      height: 32,
      placeholderColor: 0xd7a64c,
      sourceAvailable: true,
    },
    'chapter4-paper-stack': {
      path: new URL('../assets/chapter4/decor/paper_stack.png', import.meta.url).href,
      width: 32,
      height: 32,
      placeholderColor: 0xc7aa79,
      sourceAvailable: true,
    },
    'chapter4-scattered-pages': {
      path: new URL('../assets/chapter4/decor/scattered_pages.png', import.meta.url).href,
      width: 32,
      height: 32,
      placeholderColor: 0xc7aa79,
      sourceAvailable: true,
    },
    'chapter4-small-stool': {
      path: new URL('../assets/chapter4/decor/small_stool.png', import.meta.url).href,
      width: 32,
      height: 32,
      placeholderColor: 0x744323,
      sourceAvailable: true,
    },
    'chapter4-side-table-books': {
      path: new URL('../assets/chapter4/decor/side_table_books.png', import.meta.url).href,
      width: 32,
      height: 32,
      placeholderColor: 0x744323,
      sourceAvailable: true,
    },
    'chapter4-potted-plant-variant': {
      path: new URL('../assets/chapter4/decor/potted_plant_variant.png', import.meta.url).href,
      width: 32,
      height: 32,
      placeholderColor: 0x627354,
      sourceAvailable: true,
    },
  },
  floor: { assetKey: 'chapter1-floor-tileset', frameCount: 8 },
  walls: {
    perspectiveBoundary: true,
    followFloorSilhouette: true,
    top: 'chapter1-wall-unified-top',
    bottom: 'chapter1-wall-unified-bottom',
    left: 'chapter1-wall-unified-left',
    right: 'chapter1-wall-unified-right',
    cornerTopLeft: 'chapter1-wall-unified-corner-tl',
    cornerTopRight: 'chapter1-wall-unified-corner-tr',
    cornerBottomLeft: 'chapter1-wall-unified-corner-bl',
    cornerBottomRight: 'chapter1-wall-unified-corner-br',
  },
  typeVisuals: {
    door: {
      depth: 0.7,
      offset: { x: 0, y: -16 },
      displaySize: { width: 32, height: 48 },
    },
  },
  objectVisuals: {
    'chapter4-entry-bookshelf': WALL_ATTACHED_BOOKSHELF_VISUAL,
    'chapter4-archive-bookshelf-center': WALL_ATTACHED_BOOKSHELF_VISUAL,
    'chapter4-portrait-clue': { depth: 0.65 },
    'chapter4-book-clue': { depth: 0.65 },
    'chapter4-painting-clue': { depth: 0.65 },
    'chapter4-wall-clock': {
      depth: 0.65,
      offsetsByState: { moved: { x: -8, y: 8 } },
    },
    'chapter4-exit-door': {
      positionOverride: { x: 26, y: 11 },
      offset: { x: -16, y: -16 },
      displaySize: { width: 48, height: 64 },
    },
    'chapter4-entry-arch': {
      positionOverride: { x: 0, y: 2 },
      offset: { x: 0, y: -16 },
      displaySize: { width: 48, height: 64 },
    },
  },
};
