import { CHAPTER1_ASSET_MANIFEST } from '../chapter1/manifest';
import type { AssetDefinition, AssetManifest } from '../asset-definition';

/**
 * Chapter 2 keeps the current pixel-art family, but owns its asset keys so
 * the chapter can replace individual art later without touching level JSON.
 */
function alias(assetKey: keyof typeof CHAPTER1_ASSET_MANIFEST): AssetDefinition {
  const asset = CHAPTER1_ASSET_MANIFEST[assetKey];
  if (!asset) throw new Error(`Chapter 1 에셋을 찾을 수 없습니다: ${assetKey}`);
  return asset;
}

export const CHAPTER2_ASSET_MANIFEST: AssetManifest = {
  'chapter2-floor-tileset': {
    path: new URL('./tiles/floor_tileset.png', import.meta.url).href,
    width: 256,
    height: 32,
    placeholderColor: 0x171820,
    sourceAvailable: true,
    kind: 'spritesheet',
    frameWidth: 32,
    frameHeight: 32,
  },
  'chapter2-partition-tileset': {
    path: new URL('../chapter1/tiles/wall_tileset_room.png', import.meta.url).href,
    width: 256,
    height: 32,
    placeholderColor: 0x8a6045,
    sourceAvailable: true,
    kind: 'spritesheet',
    frameWidth: 32,
    frameHeight: 32,
  },
  'chapter2-wall-top': alias('chapter1-wall-top'),
  'chapter2-wall-bottom': alias('chapter1-wall-bottom'),
  'chapter2-wall-left': alias('chapter1-wall-left'),
  'chapter2-wall-right': alias('chapter1-wall-right'),
  'chapter2-wall-corner-tl': alias('chapter1-wall-corner-tl'),
  'chapter2-wall-corner-tr': alias('chapter1-wall-corner-tr'),
  'chapter2-wall-corner-bl': alias('chapter1-wall-corner-bl'),
  'chapter2-wall-corner-br': alias('chapter1-wall-corner-br'),
  'chapter2-wall-bottom-doorway': alias('chapter1-wall-bottom-doorway'),
  'chapter2-wall-unified-top': alias('chapter1-wall-unified-top'),
  'chapter2-wall-unified-bottom': alias('chapter1-wall-unified-bottom'),
  'chapter2-wall-unified-left': alias('chapter1-wall-unified-left'),
  'chapter2-wall-unified-right': alias('chapter1-wall-unified-right'),
  'chapter2-wall-unified-corner-tl': alias('chapter1-wall-unified-corner-tl'),
  'chapter2-wall-unified-corner-tr': alias('chapter1-wall-unified-corner-tr'),
  'chapter2-wall-unified-corner-bl': alias('chapter1-wall-unified-corner-bl'),
  'chapter2-wall-unified-corner-br': alias('chapter1-wall-unified-corner-br'),
  'chapter2-bed': {
    path: new URL('./furniture/bed_navy.png', import.meta.url).href,
    width: 96,
    height: 128,
    placeholderColor: 0x172848,
    sourceAvailable: true,
  },
  'chapter2-nightstand': alias('chapter1-nightstand'),
  'chapter2-window': alias('chapter1-window'),
  'chapter2-portrait': alias('chapter1-portrait'),
  'chapter2-desk': alias('chapter1-desk'),
  'chapter2-chair': alias('chapter1-chair'),
  'chapter2-rug': alias('chapter1-rug'),
  'chapter2-bookshelf-standing': alias('chapter1-bookshelf-standing'),
  'chapter2-potted-plant': alias('chapter1-potted-plant'),
  'chapter2-crate': alias('chapter1-crate'),
  'chapter2-barrel': alias('chapter1-barrel'),
  'chapter2-door-closed': alias('chapter1-door-closed'),
  'chapter2-door-open': alias('chapter1-door-open'),
  'chapter2-central-gate-closed': {
    path: new URL('./puzzle/central_gate_closed.png', import.meta.url).href,
    width: 96,
    height: 96,
    placeholderColor: 0x5f422d,
    sourceAvailable: true,
  },
  'chapter2-central-gate-open': {
    path: new URL('./puzzle/central_gate_open.png', import.meta.url).href,
    width: 96,
    height: 96,
    placeholderColor: 0x5f422d,
    sourceAvailable: true,
  },
  'chapter2-central-gate-bars': {
    path: new URL('./puzzle/central_gate_bars.png', import.meta.url).href,
    width: 32,
    height: 60,
    placeholderColor: 0x473426,
    sourceAvailable: true,
  },
  'chapter2-door-right-closed': {
    path: new URL('./puzzle/door_right_closed.png', import.meta.url).href,
    width: 96,
    height: 96,
    placeholderColor: 0x6a452d,
    sourceAvailable: true,
  },
  'chapter2-door-right-open': {
    path: new URL('./puzzle/door_right_open.png', import.meta.url).href,
    width: 96,
    height: 96,
    placeholderColor: 0x6a452d,
    sourceAvailable: true,
  },
  'chapter2-pressure-plate-inactive': {
    path: new URL('./puzzle/pressure_plate_inactive.png', import.meta.url).href,
    width: 64,
    height: 64,
    placeholderColor: 0x4e4b4d,
    sourceAvailable: true,
  },
  'chapter2-pressure-plate-active': {
    path: new URL('./puzzle/pressure_plate_active.png', import.meta.url).href,
    width: 64,
    height: 64,
    placeholderColor: 0x4f91ac,
    sourceAvailable: true,
  },
  'chapter2-candle': {
    path: new URL('./decor/candle.png', import.meta.url).href,
    width: 32,
    height: 48,
    placeholderColor: 0xd7a64a,
    sourceAvailable: true,
  },
  'chapter2-flower-table': {
    path: new URL('./decor/flower-table.png', import.meta.url).href,
    width: 64,
    height: 96,
    placeholderColor: 0xb56b75,
    sourceAvailable: true,
  },
  'chapter2-wall-painting': {
    path: new URL('./decor/wall-painting.png', import.meta.url).href,
    width: 48,
    height: 64,
    placeholderColor: 0x8e6747,
    sourceAvailable: true,
  },
  'chapter2-memory-socket': {
    path: new URL('./decor/memory-socket.png', import.meta.url).href,
    width: 64,
    height: 64,
    placeholderColor: 0x4e4b4d,
    sourceAvailable: true,
  },
  'chapter2-lever': {
    path: new URL('./decor/lever.png', import.meta.url).href,
    width: 64,
    height: 64,
    placeholderColor: 0xa87931,
    sourceAvailable: true,
  },
};
